## YAML Template.
---
logging:
  ref: STDOUT
  config: classpath:config/logback-spring.xml

server:
  port : 8090

spring:
  security:
    oauth2:
      client:
        registration:
          auth-server-sample:
            client-id: messaging-client
            client-secret: secret
#            scope: openid+profile
            scope: openid
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          auth-server-sample:
            issuer-uri: http://localhost:8080
            authorization-uri: http://localhost:8080/oauth2/authorize
            token-uri: http://localhost:8080/oauth2/token
            user-info-uri: http://localhost:8080/userinfo
            jwk-set-uri: http://localhost:8080/oauth2/jwks
            end_session_endpoint: http://localhost:8080/connect/logout
